import torch
import torchvision
import define_model
from zoobot.pytorch.estimators import efficientnet_standard, resnet_torchvision_custom

def copy_Zoobot_weights_to_Resnet(model, ckpt_path, device):
    """Returns a model that with pretrained weights from Zoobot.

    Args:
      model: a Resnet model with a standard architecture and parameter names
      ckpt_path: a full path to the Zoobot checkpoint 
      device: torch device

    Returns:
      A Pytorch model
    """

    # load Zoobot (Resnet) and checkpoint
    import define_model
    zoobot = define_model.ZoobotLightningModule(
        output_dim=34,
        question_index_groups=['idx1', 'idx2'],
        include_top=True,
        channels=3,
        use_imagenet_weights=False,
        always_augment=True,
        dropout_rate=0.2,
        architecture_name='resnet_torchvision'
    )
    checkpoint = torch.load(ckpt_path, map_location=torch.device(device))
    zoobot.load_state_dict(checkpoint['state_dict'])

    # copy the weights
    model.backbone.body.conv1.weight = zoobot.model[0][0].weight
    model.backbone.body.bn1.weight = zoobot.model[0][1].weight
    model.backbone.body.bn1.bias = zoobot.model[0][1].bias
    model.backbone.body.bn1.running_mean = zoobot.model[0][1].running_mean
    model.backbone.body.bn1.running_var = zoobot.model[0][1].running_var
    model.backbone.body.layer1[0].conv1.weight = zoobot.model[0][4][0].conv1.weight
    model.backbone.body.layer1[0].bn1.weight = zoobot.model[0][4][0].bn1.weight
    model.backbone.body.layer1[0].bn1.bias = zoobot.model[0][4][0].bn1.bias
    model.backbone.body.layer1[0].bn1.running_mean = zoobot.model[0][4][0].bn1.running_mean
    model.backbone.body.layer1[0].bn1.running_var = zoobot.model[0][4][0].bn1.running_var
    model.backbone.body.layer1[0].conv2.weight = zoobot.model[0][4][0].conv2.weight
    model.backbone.body.layer1[0].bn2.weight = zoobot.model[0][4][0].bn2.weight
    model.backbone.body.layer1[0].bn2.bias = zoobot.model[0][4][0].bn2.bias
    model.backbone.body.layer1[0].bn2.running_mean = zoobot.model[0][4][0].bn2.running_mean
    model.backbone.body.layer1[0].bn2.running_var = zoobot.model[0][4][0].bn2.running_var
    model.backbone.body.layer1[0].conv3.weight = zoobot.model[0][4][0].conv3.weight
    model.backbone.body.layer1[0].bn3.weight = zoobot.model[0][4][0].bn3.weight
    model.backbone.body.layer1[0].bn3.bias = zoobot.model[0][4][0].bn3.bias
    model.backbone.body.layer1[0].bn3.running_mean = zoobot.model[0][4][0].bn3.running_mean
    model.backbone.body.layer1[0].bn3.running_var = zoobot.model[0][4][0].bn3.running_var
    model.backbone.body.layer1[0].downsample[0].weight = zoobot.model[0][4][0].downsample[0].weight
    model.backbone.body.layer1[0].downsample[1].weight = zoobot.model[0][4][0].downsample[1].weight
    model.backbone.body.layer1[0].downsample[1].bias = zoobot.model[0][4][0].downsample[1].bias
    model.backbone.body.layer1[0].downsample[1].running_mean = zoobot.model[0][4][0].downsample[1].running_mean
    model.backbone.body.layer1[0].downsample[1].running_var = zoobot.model[0][4][0].downsample[1].running_var
    model.backbone.body.layer1[1].conv1.weight = zoobot.model[0][4][1].conv1.weight
    model.backbone.body.layer1[1].bn1.weight = zoobot.model[0][4][1].bn1.weight
    model.backbone.body.layer1[1].bn1.bias = zoobot.model[0][4][1].bn1.bias
    model.backbone.body.layer1[1].bn1.running_mean = zoobot.model[0][4][1].bn1.running_mean
    model.backbone.body.layer1[1].bn1.running_var = zoobot.model[0][4][1].bn1.running_var
    model.backbone.body.layer1[1].conv2.weight = zoobot.model[0][4][1].conv2.weight
    model.backbone.body.layer1[1].bn2.weight = zoobot.model[0][4][1].bn2.weight
    model.backbone.body.layer1[1].bn2.bias = zoobot.model[0][4][1].bn2.bias
    model.backbone.body.layer1[1].bn2.running_mean = zoobot.model[0][4][1].bn2.running_mean
    model.backbone.body.layer1[1].bn2.running_var = zoobot.model[0][4][1].bn2.running_var
    model.backbone.body.layer1[1].conv3.weight = zoobot.model[0][4][1].conv3.weight
    model.backbone.body.layer1[1].bn3.weight = zoobot.model[0][4][1].bn3.weight
    model.backbone.body.layer1[1].bn3.bias = zoobot.model[0][4][1].bn3.bias
    model.backbone.body.layer1[1].bn3.running_mean = zoobot.model[0][4][1].bn3.running_mean
    model.backbone.body.layer1[1].bn3.running_var = zoobot.model[0][4][1].bn3.running_var
    model.backbone.body.layer1[2].conv1.weight = zoobot.model[0][4][2].conv1.weight
    model.backbone.body.layer1[2].bn1.weight = zoobot.model[0][4][2].bn1.weight
    model.backbone.body.layer1[2].bn1.bias = zoobot.model[0][4][2].bn1.bias
    model.backbone.body.layer1[2].bn1.running_mean = zoobot.model[0][4][2].bn1.running_mean
    model.backbone.body.layer1[2].bn1.running_var = zoobot.model[0][4][2].bn1.running_var
    model.backbone.body.layer1[2].conv2.weight = zoobot.model[0][4][2].conv2.weight
    model.backbone.body.layer1[2].bn2.weight = zoobot.model[0][4][2].bn2.weight
    model.backbone.body.layer1[2].bn2.bias = zoobot.model[0][4][2].bn2.bias
    model.backbone.body.layer1[2].bn2.running_mean = zoobot.model[0][4][2].bn2.running_mean
    model.backbone.body.layer1[2].bn2.running_var = zoobot.model[0][4][2].bn2.running_var
    model.backbone.body.layer1[2].conv3.weight = zoobot.model[0][4][2].conv3.weight
    model.backbone.body.layer1[2].bn3.weight = zoobot.model[0][4][2].bn3.weight
    model.backbone.body.layer1[2].bn3.bias = zoobot.model[0][4][2].bn3.bias
    model.backbone.body.layer1[2].bn3.running_mean = zoobot.model[0][4][2].bn3.running_mean
    model.backbone.body.layer1[2].bn3.running_var = zoobot.model[0][4][2].bn3.running_var
    model.backbone.body.layer2[0].conv1.weight = zoobot.model[0][5][0].conv1.weight
    model.backbone.body.layer2[0].bn1.weight = zoobot.model[0][5][0].bn1.weight
    model.backbone.body.layer2[0].bn1.bias = zoobot.model[0][5][0].bn1.bias
    model.backbone.body.layer2[0].bn1.running_mean = zoobot.model[0][5][0].bn1.running_mean
    model.backbone.body.layer2[0].bn1.running_var = zoobot.model[0][5][0].bn1.running_var
    model.backbone.body.layer2[0].conv2.weight = zoobot.model[0][5][0].conv2.weight
    model.backbone.body.layer2[0].bn2.weight = zoobot.model[0][5][0].bn2.weight
    model.backbone.body.layer2[0].bn2.bias = zoobot.model[0][5][0].bn2.bias
    model.backbone.body.layer2[0].bn2.running_mean = zoobot.model[0][5][0].bn2.running_mean
    model.backbone.body.layer2[0].bn2.running_var = zoobot.model[0][5][0].bn2.running_var
    model.backbone.body.layer2[0].conv3.weight = zoobot.model[0][5][0].conv3.weight
    model.backbone.body.layer2[0].bn3.weight = zoobot.model[0][5][0].bn3.weight
    model.backbone.body.layer2[0].bn3.bias = zoobot.model[0][5][0].bn3.bias
    model.backbone.body.layer2[0].bn3.running_mean = zoobot.model[0][5][0].bn3.running_mean
    model.backbone.body.layer2[0].bn3.running_var = zoobot.model[0][5][0].bn3.running_var
    model.backbone.body.layer2[0].downsample[0].weight = zoobot.model[0][5][0].downsample[0].weight
    model.backbone.body.layer2[0].downsample[1].weight = zoobot.model[0][5][0].downsample[1].weight
    model.backbone.body.layer2[0].downsample[1].bias = zoobot.model[0][5][0].downsample[1].bias
    model.backbone.body.layer2[0].downsample[1].running_mean = zoobot.model[0][5][0].downsample[1].running_mean
    model.backbone.body.layer2[0].downsample[1].running_var = zoobot.model[0][5][0].downsample[1].running_var
    model.backbone.body.layer2[1].conv1.weight = zoobot.model[0][5][1].conv1.weight
    model.backbone.body.layer2[1].bn1.weight = zoobot.model[0][5][1].bn1.weight
    model.backbone.body.layer2[1].bn1.bias = zoobot.model[0][5][1].bn1.bias
    model.backbone.body.layer2[1].bn1.running_mean = zoobot.model[0][5][1].bn1.running_mean
    model.backbone.body.layer2[1].bn1.running_var = zoobot.model[0][5][1].bn1.running_var
    model.backbone.body.layer2[1].conv2.weight = zoobot.model[0][5][1].conv2.weight
    model.backbone.body.layer2[1].bn2.weight = zoobot.model[0][5][1].bn2.weight
    model.backbone.body.layer2[1].bn2.bias = zoobot.model[0][5][1].bn2.bias
    model.backbone.body.layer2[1].bn2.running_mean = zoobot.model[0][5][1].bn2.running_mean
    model.backbone.body.layer2[1].bn2.running_var = zoobot.model[0][5][1].bn2.running_var
    model.backbone.body.layer2[1].conv3.weight = zoobot.model[0][5][1].conv3.weight
    model.backbone.body.layer2[1].bn3.weight = zoobot.model[0][5][1].bn3.weight
    model.backbone.body.layer2[1].bn3.bias = zoobot.model[0][5][1].bn3.bias
    model.backbone.body.layer2[1].bn3.running_mean = zoobot.model[0][5][1].bn3.running_mean
    model.backbone.body.layer2[1].bn3.running_var = zoobot.model[0][5][1].bn3.running_var
    model.backbone.body.layer2[2].conv1.weight = zoobot.model[0][5][2].conv1.weight
    model.backbone.body.layer2[2].bn1.weight = zoobot.model[0][5][2].bn1.weight
    model.backbone.body.layer2[2].bn1.bias = zoobot.model[0][5][2].bn1.bias
    model.backbone.body.layer2[2].bn1.running_mean = zoobot.model[0][5][2].bn1.running_mean
    model.backbone.body.layer2[2].bn1.running_var = zoobot.model[0][5][2].bn1.running_var
    model.backbone.body.layer2[2].conv2.weight = zoobot.model[0][5][2].conv2.weight
    model.backbone.body.layer2[2].bn2.weight = zoobot.model[0][5][2].bn2.weight
    model.backbone.body.layer2[2].bn2.bias = zoobot.model[0][5][2].bn2.bias
    model.backbone.body.layer2[2].bn2.running_mean = zoobot.model[0][5][2].bn2.running_mean
    model.backbone.body.layer2[2].bn2.running_var = zoobot.model[0][5][2].bn2.running_var
    model.backbone.body.layer2[2].conv3.weight = zoobot.model[0][5][2].conv3.weight
    model.backbone.body.layer2[2].bn3.weight = zoobot.model[0][5][2].bn3.weight
    model.backbone.body.layer2[2].bn3.bias = zoobot.model[0][5][2].bn3.bias
    model.backbone.body.layer2[2].bn3.running_mean = zoobot.model[0][5][2].bn3.running_mean
    model.backbone.body.layer2[2].bn3.running_var = zoobot.model[0][5][2].bn3.running_var
    model.backbone.body.layer2[3].conv1.weight = zoobot.model[0][5][3].conv1.weight
    model.backbone.body.layer2[3].bn1.weight = zoobot.model[0][5][3].bn1.weight
    model.backbone.body.layer2[3].bn1.bias = zoobot.model[0][5][3].bn1.bias
    model.backbone.body.layer2[3].bn1.running_mean = zoobot.model[0][5][3].bn1.running_mean
    model.backbone.body.layer2[3].bn1.running_var = zoobot.model[0][5][3].bn1.running_var
    model.backbone.body.layer2[3].conv2.weight = zoobot.model[0][5][3].conv2.weight
    model.backbone.body.layer2[3].bn2.weight = zoobot.model[0][5][3].bn2.weight
    model.backbone.body.layer2[3].bn2.bias = zoobot.model[0][5][3].bn2.bias
    model.backbone.body.layer2[3].bn2.running_mean = zoobot.model[0][5][3].bn2.running_mean
    model.backbone.body.layer2[3].bn2.running_var = zoobot.model[0][5][3].bn2.running_var
    model.backbone.body.layer2[3].conv3.weight = zoobot.model[0][5][3].conv3.weight
    model.backbone.body.layer2[3].bn3.weight = zoobot.model[0][5][3].bn3.weight
    model.backbone.body.layer2[3].bn3.bias = zoobot.model[0][5][3].bn3.bias
    model.backbone.body.layer2[3].bn3.running_mean = zoobot.model[0][5][3].bn3.running_mean
    model.backbone.body.layer2[3].bn3.running_var = zoobot.model[0][5][3].bn3.running_var
    model.backbone.body.layer3[0].conv1.weight = zoobot.model[0][6][0].conv1.weight
    model.backbone.body.layer3[0].bn1.weight = zoobot.model[0][6][0].bn1.weight
    model.backbone.body.layer3[0].bn1.bias = zoobot.model[0][6][0].bn1.bias
    model.backbone.body.layer3[0].bn1.running_mean = zoobot.model[0][6][0].bn1.running_mean
    model.backbone.body.layer3[0].bn1.running_var = zoobot.model[0][6][0].bn1.running_var
    model.backbone.body.layer3[0].conv2.weight = zoobot.model[0][6][0].conv2.weight
    model.backbone.body.layer3[0].bn2.weight = zoobot.model[0][6][0].bn2.weight
    model.backbone.body.layer3[0].bn2.bias = zoobot.model[0][6][0].bn2.bias
    model.backbone.body.layer3[0].bn2.running_mean = zoobot.model[0][6][0].bn2.running_mean
    model.backbone.body.layer3[0].bn2.running_var = zoobot.model[0][6][0].bn2.running_var
    model.backbone.body.layer3[0].conv3.weight = zoobot.model[0][6][0].conv3.weight
    model.backbone.body.layer3[0].bn3.weight = zoobot.model[0][6][0].bn3.weight
    model.backbone.body.layer3[0].bn3.bias = zoobot.model[0][6][0].bn3.bias
    model.backbone.body.layer3[0].bn3.running_mean = zoobot.model[0][6][0].bn3.running_mean
    model.backbone.body.layer3[0].bn3.running_var = zoobot.model[0][6][0].bn3.running_var
    model.backbone.body.layer3[0].downsample[0].weight = zoobot.model[0][6][0].downsample[0].weight
    model.backbone.body.layer3[0].downsample[1].weight = zoobot.model[0][6][0].downsample[1].weight
    model.backbone.body.layer3[0].downsample[1].bias = zoobot.model[0][6][0].downsample[1].bias
    model.backbone.body.layer3[0].downsample[1].running_mean = zoobot.model[0][6][0].downsample[1].running_mean
    model.backbone.body.layer3[0].downsample[1].running_var = zoobot.model[0][6][0].downsample[1].running_var
    model.backbone.body.layer3[1].conv1.weight = zoobot.model[0][6][1].conv1.weight
    model.backbone.body.layer3[1].bn1.weight = zoobot.model[0][6][1].bn1.weight
    model.backbone.body.layer3[1].bn1.bias = zoobot.model[0][6][1].bn1.bias
    model.backbone.body.layer3[1].bn1.running_mean = zoobot.model[0][6][1].bn1.running_mean
    model.backbone.body.layer3[1].bn1.running_var = zoobot.model[0][6][1].bn1.running_var
    model.backbone.body.layer3[1].conv2.weight = zoobot.model[0][6][1].conv2.weight
    model.backbone.body.layer3[1].bn2.weight = zoobot.model[0][6][1].bn2.weight
    model.backbone.body.layer3[1].bn2.bias = zoobot.model[0][6][1].bn2.bias
    model.backbone.body.layer3[1].bn2.running_mean = zoobot.model[0][6][1].bn2.running_mean
    model.backbone.body.layer3[1].bn2.running_var = zoobot.model[0][6][1].bn2.running_var
    model.backbone.body.layer3[1].conv3.weight = zoobot.model[0][6][1].conv3.weight
    model.backbone.body.layer3[1].bn3.weight = zoobot.model[0][6][1].bn3.weight
    model.backbone.body.layer3[1].bn3.bias = zoobot.model[0][6][1].bn3.bias
    model.backbone.body.layer3[1].bn3.running_mean = zoobot.model[0][6][1].bn3.running_mean
    model.backbone.body.layer3[1].bn3.running_var = zoobot.model[0][6][1].bn3.running_var
    model.backbone.body.layer3[2].conv1.weight = zoobot.model[0][6][2].conv1.weight
    model.backbone.body.layer3[2].bn1.weight = zoobot.model[0][6][2].bn1.weight
    model.backbone.body.layer3[2].bn1.bias = zoobot.model[0][6][2].bn1.bias
    model.backbone.body.layer3[2].bn1.running_mean = zoobot.model[0][6][2].bn1.running_mean
    model.backbone.body.layer3[2].bn1.running_var = zoobot.model[0][6][2].bn1.running_var
    model.backbone.body.layer3[2].conv2.weight = zoobot.model[0][6][2].conv2.weight
    model.backbone.body.layer3[2].bn2.weight = zoobot.model[0][6][2].bn2.weight
    model.backbone.body.layer3[2].bn2.bias = zoobot.model[0][6][2].bn2.bias
    model.backbone.body.layer3[2].bn2.running_mean = zoobot.model[0][6][2].bn2.running_mean
    model.backbone.body.layer3[2].bn2.running_var = zoobot.model[0][6][2].bn2.running_var
    model.backbone.body.layer3[2].conv3.weight = zoobot.model[0][6][2].conv3.weight
    model.backbone.body.layer3[2].bn3.weight = zoobot.model[0][6][2].bn3.weight
    model.backbone.body.layer3[2].bn3.bias = zoobot.model[0][6][2].bn3.bias
    model.backbone.body.layer3[2].bn3.running_mean = zoobot.model[0][6][2].bn3.running_mean
    model.backbone.body.layer3[2].bn3.running_var = zoobot.model[0][6][2].bn3.running_var
    model.backbone.body.layer3[3].conv1.weight = zoobot.model[0][6][3].conv1.weight
    model.backbone.body.layer3[3].bn1.weight = zoobot.model[0][6][3].bn1.weight
    model.backbone.body.layer3[3].bn1.bias = zoobot.model[0][6][3].bn1.bias
    model.backbone.body.layer3[3].bn1.running_mean = zoobot.model[0][6][3].bn1.running_mean
    model.backbone.body.layer3[3].bn1.running_var = zoobot.model[0][6][3].bn1.running_var
    model.backbone.body.layer3[3].conv2.weight = zoobot.model[0][6][3].conv2.weight
    model.backbone.body.layer3[3].bn2.weight = zoobot.model[0][6][3].bn2.weight
    model.backbone.body.layer3[3].bn2.bias = zoobot.model[0][6][3].bn2.bias
    model.backbone.body.layer3[3].bn2.running_mean = zoobot.model[0][6][3].bn2.running_mean
    model.backbone.body.layer3[3].bn2.running_var = zoobot.model[0][6][3].bn2.running_var
    model.backbone.body.layer3[3].conv3.weight = zoobot.model[0][6][3].conv3.weight
    model.backbone.body.layer3[3].bn3.weight = zoobot.model[0][6][3].bn3.weight
    model.backbone.body.layer3[3].bn3.bias = zoobot.model[0][6][3].bn3.bias
    model.backbone.body.layer3[3].bn3.running_mean = zoobot.model[0][6][3].bn3.running_mean
    model.backbone.body.layer3[3].bn3.running_var = zoobot.model[0][6][3].bn3.running_var
    model.backbone.body.layer3[4].conv1.weight = zoobot.model[0][6][4].conv1.weight
    model.backbone.body.layer3[4].bn1.weight = zoobot.model[0][6][4].bn1.weight
    model.backbone.body.layer3[4].bn1.bias = zoobot.model[0][6][4].bn1.bias
    model.backbone.body.layer3[4].bn1.running_mean = zoobot.model[0][6][4].bn1.running_mean
    model.backbone.body.layer3[4].bn1.running_var = zoobot.model[0][6][4].bn1.running_var
    model.backbone.body.layer3[4].conv2.weight = zoobot.model[0][6][4].conv2.weight
    model.backbone.body.layer3[4].bn2.weight = zoobot.model[0][6][4].bn2.weight
    model.backbone.body.layer3[4].bn2.bias = zoobot.model[0][6][4].bn2.bias
    model.backbone.body.layer3[4].bn2.running_mean = zoobot.model[0][6][4].bn2.running_mean
    model.backbone.body.layer3[4].bn2.running_var = zoobot.model[0][6][4].bn2.running_var
    model.backbone.body.layer3[4].conv3.weight = zoobot.model[0][6][4].conv3.weight
    model.backbone.body.layer3[4].bn3.weight = zoobot.model[0][6][4].bn3.weight
    model.backbone.body.layer3[4].bn3.bias = zoobot.model[0][6][4].bn3.bias
    model.backbone.body.layer3[4].bn3.running_mean = zoobot.model[0][6][4].bn3.running_mean
    model.backbone.body.layer3[4].bn3.running_var = zoobot.model[0][6][4].bn3.running_var
    model.backbone.body.layer3[5].conv1.weight = zoobot.model[0][6][5].conv1.weight
    model.backbone.body.layer3[5].bn1.weight = zoobot.model[0][6][5].bn1.weight
    model.backbone.body.layer3[5].bn1.bias = zoobot.model[0][6][5].bn1.bias
    model.backbone.body.layer3[5].bn1.running_mean = zoobot.model[0][6][5].bn1.running_mean
    model.backbone.body.layer3[5].bn1.running_var = zoobot.model[0][6][5].bn1.running_var
    model.backbone.body.layer3[5].conv2.weight = zoobot.model[0][6][5].conv2.weight
    model.backbone.body.layer3[5].bn2.weight = zoobot.model[0][6][5].bn2.weight
    model.backbone.body.layer3[5].bn2.bias = zoobot.model[0][6][5].bn2.bias
    model.backbone.body.layer3[5].bn2.running_mean = zoobot.model[0][6][5].bn2.running_mean
    model.backbone.body.layer3[5].bn2.running_var = zoobot.model[0][6][5].bn2.running_var
    model.backbone.body.layer3[5].conv3.weight = zoobot.model[0][6][5].conv3.weight
    model.backbone.body.layer3[5].bn3.weight = zoobot.model[0][6][5].bn3.weight
    model.backbone.body.layer3[5].bn3.bias = zoobot.model[0][6][5].bn3.bias
    model.backbone.body.layer3[5].bn3.running_mean = zoobot.model[0][6][5].bn3.running_mean
    model.backbone.body.layer3[5].bn3.running_var = zoobot.model[0][6][5].bn3.running_var
    model.backbone.body.layer4[0].conv1.weight = zoobot.model[0][7][0].conv1.weight
    model.backbone.body.layer4[0].bn1.weight = zoobot.model[0][7][0].bn1.weight
    model.backbone.body.layer4[0].bn1.bias = zoobot.model[0][7][0].bn1.bias
    model.backbone.body.layer4[0].bn1.running_mean = zoobot.model[0][7][0].bn1.running_mean
    model.backbone.body.layer4[0].bn1.running_var = zoobot.model[0][7][0].bn1.running_var
    model.backbone.body.layer4[0].conv2.weight = zoobot.model[0][7][0].conv2.weight
    model.backbone.body.layer4[0].bn2.weight = zoobot.model[0][7][0].bn2.weight
    model.backbone.body.layer4[0].bn2.bias = zoobot.model[0][7][0].bn2.bias
    model.backbone.body.layer4[0].bn2.running_mean = zoobot.model[0][7][0].bn2.running_mean
    model.backbone.body.layer4[0].bn2.running_var = zoobot.model[0][7][0].bn2.running_var
    model.backbone.body.layer4[0].conv3.weight = zoobot.model[0][7][0].conv3.weight
    model.backbone.body.layer4[0].bn3.weight = zoobot.model[0][7][0].bn3.weight
    model.backbone.body.layer4[0].bn3.bias = zoobot.model[0][7][0].bn3.bias
    model.backbone.body.layer4[0].bn3.running_mean = zoobot.model[0][7][0].bn3.running_mean
    model.backbone.body.layer4[0].bn3.running_var = zoobot.model[0][7][0].bn3.running_var
    model.backbone.body.layer4[0].downsample[0].weight = zoobot.model[0][7][0].downsample[0].weight
    model.backbone.body.layer4[0].downsample[1].weight = zoobot.model[0][7][0].downsample[1].weight
    model.backbone.body.layer4[0].downsample[1].bias = zoobot.model[0][7][0].downsample[1].bias
    model.backbone.body.layer4[0].downsample[1].running_mean = zoobot.model[0][7][0].downsample[1].running_mean
    model.backbone.body.layer4[0].downsample[1].running_var = zoobot.model[0][7][0].downsample[1].running_var
    model.backbone.body.layer4[1].conv1.weight = zoobot.model[0][7][1].conv1.weight
    model.backbone.body.layer4[1].bn1.weight = zoobot.model[0][7][1].bn1.weight
    model.backbone.body.layer4[1].bn1.bias = zoobot.model[0][7][1].bn1.bias
    model.backbone.body.layer4[1].bn1.running_mean = zoobot.model[0][7][1].bn1.running_mean
    model.backbone.body.layer4[1].bn1.running_var = zoobot.model[0][7][1].bn1.running_var
    model.backbone.body.layer4[1].conv2.weight = zoobot.model[0][7][1].conv2.weight
    model.backbone.body.layer4[1].bn2.weight = zoobot.model[0][7][1].bn2.weight
    model.backbone.body.layer4[1].bn2.bias = zoobot.model[0][7][1].bn2.bias
    model.backbone.body.layer4[1].bn2.running_mean = zoobot.model[0][7][1].bn2.running_mean
    model.backbone.body.layer4[1].bn2.running_var = zoobot.model[0][7][1].bn2.running_var
    model.backbone.body.layer4[1].conv3.weight = zoobot.model[0][7][1].conv3.weight
    model.backbone.body.layer4[1].bn3.weight = zoobot.model[0][7][1].bn3.weight
    model.backbone.body.layer4[1].bn3.bias = zoobot.model[0][7][1].bn3.bias
    model.backbone.body.layer4[1].bn3.running_mean = zoobot.model[0][7][1].bn3.running_mean
    model.backbone.body.layer4[1].bn3.running_var = zoobot.model[0][7][1].bn3.running_var
    model.backbone.body.layer4[2].conv1.weight = zoobot.model[0][7][2].conv1.weight
    model.backbone.body.layer4[2].bn1.weight = zoobot.model[0][7][2].bn1.weight
    model.backbone.body.layer4[2].bn1.bias = zoobot.model[0][7][2].bn1.bias
    model.backbone.body.layer4[2].bn1.running_mean = zoobot.model[0][7][2].bn1.running_mean
    model.backbone.body.layer4[2].bn1.running_var = zoobot.model[0][7][2].bn1.running_var
    model.backbone.body.layer4[2].conv2.weight = zoobot.model[0][7][2].conv2.weight
    model.backbone.body.layer4[2].bn2.weight = zoobot.model[0][7][2].bn2.weight
    model.backbone.body.layer4[2].bn2.bias = zoobot.model[0][7][2].bn2.bias
    model.backbone.body.layer4[2].bn2.running_mean = zoobot.model[0][7][2].bn2.running_mean
    model.backbone.body.layer4[2].bn2.running_var = zoobot.model[0][7][2].bn2.running_var
    model.backbone.body.layer4[2].conv3.weight = zoobot.model[0][7][2].conv3.weight
    model.backbone.body.layer4[2].bn3.weight = zoobot.model[0][7][2].bn3.weight
    model.backbone.body.layer4[2].bn3.bias = zoobot.model[0][7][2].bn3.bias
    model.backbone.body.layer4[2].bn3.running_mean = zoobot.model[0][7][2].bn3.running_mean
    model.backbone.body.layer4[2].bn3.running_var = zoobot.model[0][7][2].bn3.running_var

    return model